### ISSUE TITLE
info  - unhandled socket.io url

### ISSUE THREAD

**Issue by ghost** [fardog/grunt-connect-socket.io#2]
I read guide at https://www.npmjs.com/package/grunt-connect-socket.io
[GitHub](https://www.npmjs.com/package/grunt-connect-socket.io) and once I enabled `socketio` at `grunt.config.data.connect` and added following code to my `server.js` file:

```
var grunt = require('grunt');
var config = grunt.config.data.connect.use_socket_io;
var socketio = config.socketio;`

socketio.sockets.on('connection', function(socket) {
    socket.emit('test', {message: "Hello!"});
});
```

It says `info  - unhandled socket.io url`. I wanted to make sure that `var config` gets proper value. So I console logged `grunt.config.data.connect` and I didn't found any key with name `use_socket_io`. I also console logged `grunt.config.data` and I couldn't find any reference to socketio except `socketio: true` under `grunt.config.data.connect`. 

How I can fix this and could this be a bug?

**Comment by fardog** [comment]
Hi @amiral84; this package is no longer maintained—its functionality was merged into `grunt-contrib-connect` ages ago, and you should've received a deprecation warning when trying to install this package. Please use `grunt-contrib-connect`, following this example: https://github.com/gruntjs/grunt-contrib-connect#oncreateserver

**Comment by ghost** [comment]
Hi Fardog, I thought so. I have tried that before but I couldn't even get socketio connected via `onCreateServer`.

**Comment by fardog** [comment]
@amiral84 sorry to hear that; I'd recommend filing an issue on `grunt-contrib-connect` if you haven't already to see if they're able to solve it; I haven't done any work with socket.io (or grunt) in a few years now, so don't have any real knowledge of how to use it with grunt/connect any longer. best of luck!

**Comment by ghost** [comment]
@fardog Thanks for your help, I will file an issue to there :)
